name: format
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
jobs:
  lint:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all --check
